### ISSUE TITLE
Window gets black

### ISSUE THREAD

**Issue by d0iasm** [hikalium/liumos#64]
When brower-rs.bin is executed on liumos, an application window gets black once it is overridden by a cursor or it is moved.

https://user-images.githubusercontent.com/12879646/135707367-e3a39696-1408-4778-ad40-ae38cd3f1d57.mov

**Comment by hikalium** [comment]
Thanks for the report! I found that it was a problem about how we are allocating a Sheet buffer for apps: it was pointing a user mode memory region, which is not mapped when we move the sheet, so Flush() copies literary "zero" data that results in a black screen.

**Comment by hikalium** [comment]
Mark as fixed.
